[package]
name = "xtask"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
elasticctl-core.workspace = true
elasticctl-api.workspace = true
serde_json.workspace = true
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "process", "io-util"] }
